apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prerelease-front-end
  namespace: test-cli-prod
  labels:
    project: test-cli
    owner: topgroup
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: route
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: ''
spec:
  tls:
    - hosts:
        - test-cli-front-end.prerelease.diginext.site
      secretName: secret-test-cli-front-end-prerelease-diginext-site
  rules:
    - host: test-cli-front-end.prerelease.diginext.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-end-2022-12-30-16-53-20
                port:
                  number: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: front-end-2022-12-30-16-53-20
  namespace: test-cli-prod
  labels:
    app: front-end-2022-12-30-16-53-20
    project: test-cli
    owner: topgroup
    main-app: front-end
    phase: prerelease
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: front-end-2022-12-30-16-53-20
  sessionAffinity: ClientIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-2022-12-30-16-53-20
  namespace: test-cli-prod
  labels:
    project: test-cli
    owner: topgroup
    phase: prerelease
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end-2022-12-30-16-53-20
  template:
    metadata:
      labels:
        owner: topgroup
        app: front-end-2022-12-30-16-53-20
        project: test-cli
        main-app: front-end
    spec:
      containers:
        - name: front-end
          image: asia.gcr.io/top-group-k8s/test-cli/front-end:2022-12-30-16-53-20
          ports:
            - containerPort: 3000
          resources: {}
          env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
            - name: PORT
              value: '3000'
            - name: NODE_PORT
              value: '3000'
            - name: NODE_ENV
              value: production
            - name: BASE_PATH
              value: ''
            - name: NODE_URL
              value: https://test-cli-front-end.prerelease.diginext.site
      imagePullSecrets:
        - name: gcloud-docker-registry-key

---
